{{- if .Values.cronJobs }}
{{- range $k, $job := .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $job.name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ $job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ $job.name }}
              image: {{ $job.image }}
              {{- if $job.command }}
              command:
                {{ toYaml $job.command.cmd | nindent 16 | trim }}
              {{- end }}
          restartPolicy: OnFailure
---
{{- end }}
{{- end }}
