{{- if .Values.hpa }}
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.application_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.application_name }}
spec:
  minReplicas: {{ .Values.hpa.min }}
  maxReplicas: {{ .Values.hpa.max }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.application_name }}
  metrics:
      {{- if .Values.hpa.cpuAverageUtilization}}
      - type: Resource
        resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: {{ .Values.hpa.cpuAverageUtilization }}
      {{- end}}
      {{- if .Values.hpa.memoryAverageUtilization}}
      - type: Resource
        resource:
            name: memory
            target:
                type: Utilization
                averageUtilization: {{ .Values.hpa.memoryAverageUtilization }}
      {{- end}}

{{- end }}
{{- end }}
